# Setup
title:        ECCE (on GitHub)
tagline:      Fostering innovation and excellence in GIS
baseurl:      ""
githuburl:    https://github.com/EsriCanada-CE
ghpagesroot:  https://esricanada-ce.github.io

# About/contact
author:
  name:       Esri Canada GIS Centres of Excellence
  url:        https://ecce.esri.ca

#Others
markdown: kramdown
port: 12349
host: 0.0.0.0

collections:
  appchallenge:
    output: true

exclude:
  - _appchallenge/2022/example_team.md
  - _appchallenge/2023/example_team.md
  - _appchallenge/2024/example_team.md
  - _appchallenge/2025/example_team.md
  - _appchallenge/2026/example_team.md
  - _appchallenge/2027/example_team.md
  - _appchallenge/2028/example_team.md
  - _appchallenge/2029/example_team.md
  - _appchallenge/2030/example_team.md
  - _appchallenge/2031/example_team.md
  - _appchallenge/2032/example_team.md
  - _appchallenge/2033/example_team.md
  - _appchallenge/2034/example_team.md
  - _appchallenge/2035/example_team.md
  - _appchallenge/2036/example_team.md
