# Setup
title:        ECCE (on GitHub)
tagline:      Fostering innovation and excellence in GIS
baseurl:      ""
githuburl:    https://github.com/EsriCanada-CE
ghpagesroot:  https://esricanada-ce.github.io

# About/contact
author:
  name:       Esri Canada GIS Centres of Excellence
  url:        https://ecce.esri.ca

#Others
markdown: kramdown
port: 12349
host: 0.0.0.0

collections:
  appchallenge:
    output: true

exclude:
  - _appchallenge/2022/example_team.md
